services:
  # Isolated Docker daemon for jobs (Docker-in-Docker)
  dind:
    image: docker:27-dind
    privileged: true # required by dind
    command:
      # tweak as needed
      - "--mtu=1450"
      - "--dns=10.111.1.2"
      - "--dns=10.111.1.3"
    environment:
      DOCKER_BUILDKIT: "1"
      DOCKER_TLS_CERTDIR: ""
    healthcheck:
      test: ["CMD", "docker", "info"]
      interval: 5s
      timeout: 3s
      retries: 20

  gha-runner:
    build: .
    cpus: 8
    depends_on:
      dind:
        condition: service_healthy
    restart: unless-stopped
    environment:
      ACTIONS_RUNNER_TOOL_CACHE: /home/runner/_tools
      GITHUB_PAT: ${GITHUB_PAT}
      RUNNER_LABELS: self-hosted,linux,x64,large
      RUNNER_NAME_PREFIX: large
      RUNNER_URL: https://github.com/twin-digital/common-lift
      RUNNER_WORKDIR: /home/runner/_work
      DOCKER_HOST: tcp://dind:2375
      DOCKER_BUILDKIT: "1"
    network_mode: "service:dind"
    volumes:
      - runner-tools:/home/runner/_tools # caches workspace/tools between container restarts
      - runner-work:/home/runner/_work

volumes:
  runner-tools:
  runner-work:
