services:
  # Isolated Docker daemon for jobs (Docker-in-Docker)
  dind:
    image: docker:27-dind
    privileged: true # required by dind
    command:
      # tweak as needed
      - "--mtu=1450"
      - "--dns=10.111.1.2"
      - "--dns=10.111.1.3"
    environment:
      DOCKER_BUILDKIT: "1"
      DOCKER_TLS_CERTDIR: ""
    healthcheck:
      test: ["CMD", "docker", "info"]
      interval: 5s
      timeout: 3s
      retries: 20

  gha-runner:
    build: .
    depends_on:
      dind:
        condition: service_healthy
    restart: unless-stopped
    environment:
      ACTIONS_RUNNER_TOOL_CACHE: /home/runner/_tools
      GITHUB_PAT: ${GITHUB_PAT}
      RUNNER_LABELS: self-hosted,linux,x64,large
      RUNNER_NAME_PREFIX: large
      RUNNER_URL: https://github.com/twin-digital/common-lift
      RUNNER_WORKDIR: /home/runner/_work
      DOCKER_HOST: tcp://dind:2375
      DOCKER_BUILDKIT: "1"
    volumes:
      - runner-tools:/home/runner/_tools # caches workspace/tools between container restarts
      - runner-work:/home/runner/_work

  # Redirect *all* runner-local TCP (127.0.0.1:*) to dind:<same-port>; this allows jobs to access ports
  # exposed by Docker containers without knowing anything about the Docker (dind) sidecar
  # Runs in the runner's net namespace so it can rewrite OUTPUT traffic.
  loopback-redirect:
    image: alpine:3.22
    cap_add:
      - NET_ADMIN
    depends_on:
      dind:
        condition: service_started
      gha-runner:
        condition: service_started
    # share runner netns
    network_mode: "service:gha-runner"
    volumes:
      - ./redirect.sh:/usr/local/bin/redirect.sh:ro
    entrypoint: ["/bin/sh", "/usr/local/bin/redirect.sh"]

volumes:
  runner-tools:
  runner-work:
